# Generated by Django 4.2 on 2023-05-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('st_address', models.CharField(unique=True)),
                ('city', models.CharField()),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField()),
                ('addressid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_amt', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discountid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'discounts',
                'db_table': 'discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Has',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renterid', models.IntegerField()),
                ('paymentid', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'hases',
                'db_table': 'has',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('walkability_score', models.IntegerField()),
                ('crime_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('school_rating', models.CharField(max_length=1)),
                ('neighborhoodid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'neighborhoods',
                'db_table': 'neighborhood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('pmt_type', models.CharField()),
                ('card_num', models.IntegerField(unique=True)),
                ('expiration', models.CharField()),
                ('ccv', models.IntegerField()),
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('sq_ft', models.IntegerField()),
                ('no_bedrooms', models.IntegerField()),
                ('no_baths', models.IntegerField()),
                ('pool', models.CharField(max_length=1)),
                ('property_type', models.CharField()),
                ('description', models.CharField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('propertyid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealEstateOffice',
            fields=[
                ('office_ph_num', models.CharField()),
                ('officeid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'real_estate_offices',
                'db_table': 'real_estate_office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('realtorid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'realtors',
                'db_table': 'realtor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('primary_pmt', models.IntegerField()),
                ('secondary_pmt', models.IntegerField()),
                ('ssn', models.IntegerField(unique=True)),
                ('renterid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'renters',
                'db_table': 'renter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renterid', models.IntegerField()),
                ('paymentid', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'rents',
                'db_table': 'rents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('points_balance', models.IntegerField()),
                ('rewards_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'rewards',
                'db_table': 'rewards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approv_code', models.CharField(unique=True)),
                ('pmt_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('fname', models.CharField()),
                ('lname', models.CharField()),
                ('role', models.CharField(max_length=3)),
                ('ph_number', models.CharField()),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
