# Generated by Django 4.2 on 2023-04-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False, 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'managed': False, 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterModelOptions(
            name='has',
            options={'managed': False, 'verbose_name_plural': 'hases'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'managed': False, 'verbose_name_plural': 'neighborhoods'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'managed': False, 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'managed': False, 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='realestateoffice',
            options={'managed': False, 'verbose_name_plural': 'real_estate_offices'},
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'managed': False, 'verbose_name_plural': 'realtors'},
        ),
        migrations.AlterModelOptions(
            name='renter',
            options={'managed': False, 'verbose_name_plural': 'renters'},
        ),
        migrations.AlterModelOptions(
            name='rents',
            options={'managed': False, 'verbose_name_plural': 'rents'},
        ),
        migrations.AlterModelOptions(
            name='rewards',
            options={'managed': False, 'verbose_name_plural': 'rewards'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False, 'verbose_name_plural': 'transactions'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name_plural': 'users'},
        ),
    ]
